<a href="https://colab.research.google.com/github/manishrathod2003/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic NumPy Operations


1. Write a NumPy program to create a 1D array from a list [1, 2, 3, 4, 5].

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2. Create a NumPy array of shape (3, 3) filled with zeros.


In [2]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a NumPy array of shape (2, 4) filled with ones.


In [3]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Generate an array of numbers from 10 to 50 with a step of 5.


In [4]:
arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


5. Create an array of 10 evenly spaced values between 0 and 1.

In [5]:
arr = np.linspace(0, 1, 10)
print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


6. Generate a 5x5 identity matrix


In [17]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


7. Create an array of shape (3,3) with random values between 0 and 1.

In [8]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.88175594 0.91158627 0.93564792]
 [0.70591502 0.74419306 0.60432306]
 [0.21259654 0.78636646 0.60902245]]


8. Convert a Python list [10, 20, 30] into a NumPy array and print its type.


In [16]:
list = [10, 20, 30]
arr = np.array(list)
print(type(arr))


<class 'numpy.ndarray'>


9. Create an array of 10 random integers between 1 and 100.

In [15]:
random_integers = np.random.randint(1, 101, 10)
print(random_integers)


[ 44  23  26  40  74  28 100  21  82  53]


10. Generate a 4x4 array with random floating-point numbers

In [14]:
random_floats = np.random.random((4, 4))
print(random_floats)


[[0.11674898 0.48635312 0.87494858 0.76300823]
 [0.25629553 0.10659471 0.41904086 0.79626011]
 [0.81312838 0.30482244 0.81037752 0.69482892]
 [0.14758637 0.75081428 0.10313977 0.57929889]]
