<a href="https://colab.research.google.com/github/manishrathod2003/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic NumPy Operations


1. Write a NumPy program to create a 1D array from a list [1, 2, 3, 4, 5].

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2. Create a NumPy array of shape (3, 3) filled with zeros.


In [ ]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a NumPy array of shape (2, 4) filled with ones.


In [ ]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Generate an array of numbers from 10 to 50 with a step of 5.


In [ ]:
arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


5. Create an array of 10 evenly spaced values between 0 and 1.

In [ ]:
arr = np.linspace(0, 1, 10)
print(arr)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


6. Generate a 5x5 identity matrix


In [ ]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


7. Create an array of shape (3,3) with random values between 0 and 1.

In [ ]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.88175594 0.91158627 0.93564792]
 [0.70591502 0.74419306 0.60432306]
 [0.21259654 0.78636646 0.60902245]]


8. Convert a Python list [10, 20, 30] into a NumPy array and print its type.


In [ ]:
list = [10, 20, 30]
arr = np.array(list)
print(type(arr))


<class 'numpy.ndarray'>


9. Create an array of 10 random integers between 1 and 100.

In [ ]:
random_integers = np.random.randint(1, 101, 10)
print(random_integers)


[ 44  23  26  40  74  28 100  21  82  53]


10. Generate a 4x4 array with random floating-point numbers

In [ ]:
random_floats = np.random.random((4, 4))
print(random_floats)


[[0.11674898 0.48635312 0.87494858 0.76300823]
 [0.25629553 0.10659471 0.41904086 0.79626011]
 [0.81312838 0.30482244 0.81037752 0.69482892]
 [0.14758637 0.75081428 0.10313977 0.57929889]]


# Array Manipulation

11. Reshape a 1D array of 9 elements into a 3x3 matrix.


In [3]:
arr = [1,2,3,4,5,6,7,8,9]
arr = np.array(arr)
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


12. Flatten a 2D NumPy array into a 1D array.

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr.flatten()
print(arr)

[1 2 3 4 5 6]


13. Stack two NumPy arrays vertically.

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


14. Stack two NumPy arrays horizontally.

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


15. Concatenate two 1D NumPy arrays.

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


16. Split an array [1,2,3,4,5,6] into three equal parts.

In [9]:
arr = np.array([1,2,3,4,5,6])
arr = np.array_split(arr,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


17. Change the data type of a NumPy array from float to int.

In [10]:
arr = np.array([1.0,2.0,3.0])
arr = arr.astype(int)
print(arr)

[1 2 3]


18. Reverse a NumPy array.

In [13]:
arr = np.array([1,2,3,4,5,6])
arr = arr[::-1]
print(arr)

[6 5 4 3 2 1]


In [18]:
arr = np.array([1,2,3,4,5,6])
arr = np.flip(arr)
print(arr)

[6 5 4 3 2 1]


19. Find the shape and size of a given NumPy array.

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.size(arr))
print(np.shape(arr))

9
(3, 3)


20. Create an array and find its transpose.

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.transpose(arr))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Mathematical Operations

21. Add two NumPy arrays element-wise.

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.add(arr1,arr2)
print(arr)

[5 7 9]
