<a href="https://colab.research.google.com/github/manishrathod2003/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a NumPy program to create a 1D array from a list [1, 2, 3, 4, 5].

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


2. Create a NumPy array of shape (3, 3) filled with zeros.


In [2]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Create a NumPy array of shape (2, 4) filled with ones.


In [3]:
ones = np.ones((2, 4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
